import LocalDifferentials
import Mathlib.Basic.Complex.Basic
import Mathlib.RingTheory.Valuation.ValuationSubring
import Mathlib.LinearAlgebra.Dimension.Finrank

/-!
# The genus of a field over `ℂ`, without a chosen model (R01a)

The genus scope study reads "genus of the normalization" as the genus of the
function field: the dimension of the differentials that are regular at every
place. G09 proved it for the family through an explicit list of places. This
module states the same notion for an arbitrary field `K` containing `ℂ`, with no
list, so that it can be compared across isomorphic fields (R01).

* A *place* is a valuation subring `O ≠ K` containing the constants
  (`IsComplexPlace`). Discreteness is not assumed; for the fields studied here
  it is a consequence of the place classifications.
* A differential is *regular at `O`* when it is a `ℂ`-combination of differentials
  `a·db` with `a, b ∈ O` (`regularAt`). When the differentials of `O` are
  generated by one `du`, this is `ω = f·du` with `f ∈ O`
  (`mem_regularAt_iff_of_generator`), the criterion G09 used.
* The *holomorphic differentials* are those regular at every place
  (`holomorphicSpace`), and the *genus* is their dimension over `ℂ` (`genus`).

An isomorphism of `ℂ`-algebras carries places to places and regular
differentials to regular differentials, so the genus is invariant
(`genus_congr`); automorphisms preserve the holomorphic differentials
(`kaehlerTransport_mem_holomorphicSpace` with `L = K`).

Coefficients are taken in `K` on purpose: an `O`-module structure on `Ω[K⁄ℂ]`
brings back the instance diamond met in G09a-2c.
-/

namespace CurveSymmetry

set_option autoImplicit false

section Genus

variable {K : Type*} [Field K] [Algebra ℂ K]

/-- A place of `K` over `ℂ`: a valuation subring other than `K` containing the constants. -/
def IsComplexPlace (O : ValuationSubring K) : Prop :=
  O ≠ ⊤ ∧ ∀ z : ℂ, algebraMap ℂ K z ∈ O

/-- The differentials regular at `O`: the `ℂ`-combinations of `a·db` with `a, b ∈ O`. -/
noncomputable def regularAt (O : ValuationSubring K) : Submodule ℂ Ω[K⁄ℂ] :=
  Submodule.span ℂ {ω | ∃ a ∈ O, ∃ b ∈ O, ω = a • KaehlerDifferential.D ℂ K b}

lemma smul_D_mem_regularAt {O : ValuationSubring K} {a b : K} (ha : a ∈ O) (hb : b ∈ O) :
    a • KaehlerDifferential.D ℂ K b ∈ regularAt O :=
  Submodule.subset_span ⟨a, ha, b, hb, rfl⟩

/-- When every `db`, `b ∈ O`, is an `O`-multiple of one `du`, regularity at `O` is the
criterion `ω = f·du` with `f ∈ O`. -/
theorem mem_regularAt_iff_of_generator {O : ValuationSubring K} {u : K} (hu : u ∈ O)
    (hconst : ∀ z : ℂ, algebraMap ℂ K z ∈ O)
    (hgen : ∀ b ∈ O, ∃ g ∈ O,
      KaehlerDifferential.D ℂ K b = g • KaehlerDifferential.D ℂ K u)
    (ω : Ω[K⁄ℂ]) :
    ω ∈ regularAt O ↔ ∃ f ∈ O, ω = f • KaehlerDifferential.D ℂ K u := by
  constructor
  · intro hω
    induction hω using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨a, ha, b, hb, rfl⟩ := hx
      obtain ⟨g, hg, hbg⟩ := hgen b hb
      exact ⟨a * g, mul_mem ha hg, by rw [hbg, smul_smul]⟩
    | zero => exact ⟨0, O.zero_mem, by rw [zero_smul]⟩
    | add x y _ _ hx hy =>
      obtain ⟨f, hf, rfl⟩ := hx
      obtain ⟨f', hf', rfl⟩ := hy
      exact ⟨f + f', add_mem hf hf', by rw [add_smul]⟩
    | smul z x _ hx =>
      obtain ⟨f, hf, rfl⟩ := hx
      refine ⟨algebraMap ℂ K z * f, mul_mem (hconst z) hf, ?_⟩
      rw [← smul_assoc, Algebra.smul_def]
  · rintro ⟨f, hf, rfl⟩
    exact smul_D_mem_regularAt hf hu

/-- A generator of the differentials of a ring `A` inside `K` gives the generator condition of
`mem_regularAt_iff_of_generator` for the elements of `A`. -/
theorem exists_D_eq_smul_of_span_eq_top {A : Type*} [CommRing A] [Algebra ℂ A] [Algebra A K]
    [IsScalarTower ℂ A K] {u : A}
    (hu : Submodule.span A {KaehlerDifferential.D ℂ A u} = ⊤) (b : A) :
    ∃ g : A, KaehlerDifferential.D ℂ K (algebraMap A K b) =
      algebraMap A K g • KaehlerDifferential.D ℂ K (algebraMap A K u) := by
  have hb : KaehlerDifferential.D ℂ A b ∈ Submodule.span A {KaehlerDifferential.D ℂ A u} := by
    rw [hu]; trivial
  obtain ⟨g, hg⟩ := Submodule.mem_span_singleton.mp hb
  refine ⟨g, ?_⟩
  have hmap := congrArg (KaehlerDifferential.map ℂ ℂ A K) hg
  rw [map_smul, KaehlerDifferential.map_D, KaehlerDifferential.map_D] at hmap
  rw [← hmap, IsScalarTower.algebraMap_smul]

variable (K) in
/-- The holomorphic differentials: those regular at every place. -/
noncomputable def holomorphicSpace : Submodule ℂ Ω[K⁄ℂ] :=
  ⨅ (O : ValuationSubring K) (_ : IsComplexPlace O), regularAt O

theorem mem_holomorphicSpace {ω : Ω[K⁄ℂ]} :
    ω ∈ holomorphicSpace K ↔ ∀ O : ValuationSubring K, IsComplexPlace O → ω ∈ regularAt O := by
  simp only [holomorphicSpace, Submodule.mem_iInf]

variable (K) in
/-- **R01a**: the genus of `K`, the dimension over `ℂ` of its holomorphic differentials. -/
noncomputable def genus : ℕ :=
  Module.finrank ℂ (holomorphicSpace K)

end Genus

section Transport

variable {K L : Type*} [Field K] [Algebra ℂ K] [Field L] [Algebra ℂ L]

lemma kaehlerTransport_symm_apply (e : K ≃ₐ[ℂ] L) (ω : Ω[K⁄ℂ]) :
    kaehlerTransport e.symm (kaehlerTransport e ω) = ω := by
  have hω : ω ∈ Submodule.span K (Set.range (KaehlerDifferential.D ℂ K)) := by
    rw [KaehlerDifferential.span_range_derivation]; trivial
  induction hω using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨a, rfl⟩ := hx
    rw [kaehlerTransport_D, kaehlerTransport_D, AlgEquiv.symm_apply_apply]
  | zero => rw [map_zero, map_zero]
  | add x y _ _ hx hy => rw [map_add, map_add, hx, hy]
  | smul a x _ hx =>
    rw [kaehlerTransport_smul, kaehlerTransport_smul, AlgEquiv.symm_apply_apply, hx]

/-- `kaehlerTransport` along a `ℂ`-algebra isomorphism, as a `ℂ`-linear equivalence. -/
noncomputable def kaehlerTransportEquiv (e : K ≃ₐ[ℂ] L) : Ω[K⁄ℂ] ≃ₗ[ℂ] Ω[L⁄ℂ] where
  toFun := kaehlerTransport e
  invFun := kaehlerTransport e.symm
  map_add' := map_add _
  map_smul' := kaehlerTransport_smul_base e
  left_inv := kaehlerTransport_symm_apply e
  right_inv ω := by
    simpa only [AlgEquiv.symm_symm] using kaehlerTransport_symm_apply e.symm ω

@[simp] lemma kaehlerTransportEquiv_apply (e : K ≃ₐ[ℂ] L) (ω : Ω[K⁄ℂ]) :
    kaehlerTransportEquiv e ω = kaehlerTransport e ω :=
  rfl

/-- Places pull back to places along an isomorphism. -/
lemma IsComplexPlace.comap {O : ValuationSubring L} (hO : IsComplexPlace O) (e : K ≃ₐ[ℂ] L) :
    IsComplexPlace (O.comap (e : K →+* L)) := by
  refine ⟨fun htop => hO.1 ?_, fun z => ?_⟩
  · refine eq_top_iff.mpr fun y _ => ?_
    have hy : e.symm y ∈ O.comap (e : K →+* L) := by
      rw [htop]; exact ValuationSubring.mem_top _
    rw [ValuationSubring.mem_comap] at hy
    simpa using hy
  · rw [ValuationSubring.mem_comap]
    simpa using hO.2 z

/-- The transport carries differentials regular at the pulled-back place to differentials
regular at the place. -/
lemma kaehlerTransport_mem_regularAt (e : K ≃ₐ[ℂ] L) (O : ValuationSubring L)
    {ω : Ω[K⁄ℂ]} (hω : ω ∈ regularAt (O.comap (e : K →+* L))) :
    kaehlerTransport e ω ∈ regularAt O := by
  change kaehlerTransportEquiv e ω ∈ regularAt O
  have hmap : (regularAt (O.comap (e : K →+* L))).map
      (kaehlerTransportEquiv e : Ω[K⁄ℂ] →ₗ[ℂ] Ω[L⁄ℂ]) ≤ regularAt O := by
    rw [regularAt, Submodule.map_span, Submodule.span_le]
    rintro _ ⟨_, ⟨a, ha, b, hb, rfl⟩, rfl⟩
    rw [ValuationSubring.mem_comap] at ha hb
    refine Submodule.subset_span ⟨e a, ha, e b, hb, ?_⟩
    rw [LinearEquiv.coe_coe, kaehlerTransportEquiv_apply, kaehlerTransport_smul,
      kaehlerTransport_D]
  exact hmap ⟨ω, hω, rfl⟩

/-- An isomorphism of `ℂ`-algebras carries holomorphic differentials to holomorphic
differentials. With `L = K` this is invariance under automorphisms. -/
theorem kaehlerTransport_mem_holomorphicSpace (e : K ≃ₐ[ℂ] L) {ω : Ω[K⁄ℂ]}
    (hω : ω ∈ holomorphicSpace K) : kaehlerTransport e ω ∈ holomorphicSpace L := by
  rw [mem_holomorphicSpace] at hω ⊢
  exact fun O hO => kaehlerTransport_mem_regularAt e O (hω _ (hO.comap e))

theorem holomorphicSpace_map (e : K ≃ₐ[ℂ] L) :
    (holomorphicSpace K).map (kaehlerTransportEquiv e : Ω[K⁄ℂ] →ₗ[ℂ] Ω[L⁄ℂ]) =
      holomorphicSpace L := by
  apply le_antisymm
  · rintro _ ⟨ω, hω, rfl⟩
    exact kaehlerTransport_mem_holomorphicSpace e hω
  · intro ω hω
    refine ⟨kaehlerTransport e.symm ω, kaehlerTransport_mem_holomorphicSpace e.symm hω, ?_⟩
    change kaehlerTransport e (kaehlerTransport e.symm ω) = ω
    simpa only [AlgEquiv.symm_symm] using kaehlerTransport_symm_apply e.symm ω

/-- The holomorphic differentials of isomorphic fields are isomorphic. -/
noncomputable def holomorphicSpaceEquiv (e : K ≃ₐ[ℂ] L) :
    holomorphicSpace K ≃ₗ[ℂ] holomorphicSpace L :=
  ((kaehlerTransportEquiv e).submoduleMap (holomorphicSpace K)).trans
    (LinearEquiv.ofEq _ _ (holomorphicSpace_map e))

@[simp] lemma holomorphicSpaceEquiv_apply (e : K ≃ₐ[ℂ] L) (ω : holomorphicSpace K) :
    (holomorphicSpaceEquiv e ω : Ω[L⁄ℂ]) = kaehlerTransport e ω :=
  rfl

/-- **R01a**: the genus is invariant under isomorphisms of `ℂ`-algebras. -/
theorem genus_congr (e : K ≃ₐ[ℂ] L) : genus K = genus L :=
  (holomorphicSpaceEquiv e).finrank_eq

end Transport

#print axioms mem_regularAt_iff_of_generator
#print axioms exists_D_eq_smul_of_span_eq_top
#print axioms holomorphicSpaceEquiv
#print axioms genus_congr

end CurveSymmetry
