import KummerLocal
import QuarticComparison

/-!
# Places of the Kummer field over the affine line (R01c-2b)

With the Kummer ring Dedekind (R01c-2a) and the Kummer field its fraction field
(R01f), the generic `DedekindPlaces` gives, at each point `(a, b)` with
`bⁿ = f(a)`, a local ring `kummerLocalRing` inside the field and the place
`kummerPlace` with the same members. This module adds what the genus
computation of the quartic (R01e) uses:

* the place is a place over `ℂ` in the sense of R01a
  (`kummerPlace_isComplexPlace`);
* the differentials of the local ring are generated by `du` for a uniformizer
  `u` (`kummerLocal_kaehler_span_eq_top`), the residue field being `ℂ`;
* regularity of `F·dx` there: `F` in the local ring where `f(a) ≠ 0`
  (`kummer_regularAt_unramified`), `F·yⁿ⁻¹` in it where `f(a) = 0`
  (`kummer_regularAt_ramified`), because `n·yⁿ⁻¹·dy = f'(x)·dx` and `f'(x)` is a
  unit at a simple root;
* an element of the field in every point's local ring comes from the coordinate
  ring (`kummer_mem_range_of_forall_local`).
-/

namespace CurveSymmetry

set_option autoImplicit false
open Polynomial

variable {n : ℕ} [NeZero n] {f : ℂ[X]} [Fact (Squarefree f)] [Fact (0 < f.natDegree)]

instance kummerRing_isDedekindDomain' : IsDedekindDomain (KummerRing n f) :=
  kummerRing_isDedekindDomain

instance kummerRing_isFractionRing' : IsFractionRing (KummerRing n f) (KummerField n f) :=
  kummerRing_isFractionRing n f (NeZero.ne n)

instance kummerRing_scalarTower_poly : IsScalarTower ℂ[X] (KummerRing n f) (KummerField n f) :=
  IsScalarTower.of_algebraMap_eq fun p => by
    rw [kummerRing_algebraMap_apply, AlgHom.commutes]

instance kummerField_charZero : CharZero (KummerField n f) :=
  charZero_of_injective_algebraMap (algebraMap ℂ (KummerField n f)).injective

lemma kummerField_polynomial_injective :
    Function.Injective (algebraMap ℂ[X] (KummerField n f)) := by
  rw [IsScalarTower.algebraMap_eq ℂ[X] (RatFunc ℂ) (KummerField n f)]
  exact (algebraMap (RatFunc ℂ) (KummerField n f)).injective.comp
    (IsFractionRing.injective ℂ[X] (RatFunc ℂ))

section Local

variable (a b : ℂ) (hb : b ^ n = f.eval a)

/-- The local ring of the Kummer cover at the point `(a, b)`, inside the function field. -/
noncomputable abbrev kummerLocalRing : Subalgebra (KummerRing n f) (KummerField n f) :=
  primeLocalization (KummerField n f) (RingHom.ker (kummerEval n f a b hb))

/-- The place of the Kummer field at the point `(a, b)`. -/
noncomputable def kummerPlace : ValuationSubring (KummerField n f) :=
  primeValuationSubring (KummerField n f) (RingHom.ker (kummerEval n f a b hb))
    (kummerEval_ker_ne_bot a b hb)

lemma mem_kummerPlace_iff (z : KummerField n f) :
    z ∈ kummerPlace a b hb ↔ z ∈ kummerLocalRing a b hb :=
  Iff.rfl

instance kummerLocalRing_dvr : IsDiscreteValuationRing (kummerLocalRing a b hb) :=
  primeLocalization_dvr _ (kummerEval_ker_ne_bot a b hb)

noncomputable instance kummerLocalRing_essFiniteType_ring :
    Algebra.EssFiniteType (KummerRing n f) (kummerLocalRing a b hb) :=
  Algebra.EssFiniteType.of_isLocalization (S := kummerLocalRing a b hb)
    (RingHom.ker (kummerEval n f a b hb)).primeCompl

noncomputable instance kummerLocalRing_essFiniteType :
    Algebra.EssFiniteType ℂ (kummerLocalRing a b hb) :=
  Algebra.EssFiniteType.comp ℂ (KummerRing n f) (kummerLocalRing a b hb)

omit [NeZero n] [Fact (Squarefree f)] [Fact (0 < f.natDegree)] in
/-- Constants of `ℂ` represent every residue of the coordinate ring at the point. -/
theorem kummerRing_residue (s : KummerRing n f) :
    ∃ r : ℂ, s - algebraMap ℂ (KummerRing n f) r ∈ RingHom.ker (kummerEval n f a b hb) := by
  refine ⟨kummerEval n f a b hb s, ?_⟩
  have hconst : kummerEval n f a b hb (algebraMap ℂ (KummerRing n f) (kummerEval n f a b hb s)) =
      kummerEval n f a b hb s := by
    rw [IsScalarTower.algebraMap_apply ℂ ℂ[X] (KummerRing n f), kummerEval_algebraMap,
      ← Polynomial.C_eq_algebraMap, eval_C]
  rw [RingHom.mem_ker, map_sub, hconst, sub_self]

/-- **R01c-2b**: at a point, the differentials of the local ring are generated by `du` for any
generator `u` of its maximal ideal. -/
theorem kummerLocal_kaehler_span_eq_top {u : kummerLocalRing a b hb}
    (hu : IsLocalRing.maximalIdeal (kummerLocalRing a b hb) = Ideal.span {u}) :
    Submodule.span (kummerLocalRing a b hb)
      {KaehlerDifferential.D ℂ (kummerLocalRing a b hb) u} = ⊤ :=
  localKaehler_span_eq_top
    (localization_residue (RingHom.ker (kummerEval n f a b hb)) (kummerRing_residue a b hb)) hu

lemma kummerLocal_ringElem_mem (r : KummerRing n f) :
    algebraMap (KummerRing n f) (KummerField n f) r ∈ kummerLocalRing a b hb :=
  Subalgebra.algebraMap_mem _ _

lemma kummerLocal_poly_mem (p : ℂ[X]) :
    algebraMap ℂ[X] (KummerField n f) p ∈ kummerLocalRing a b hb := by
  rw [IsScalarTower.algebraMap_apply ℂ[X] (KummerRing n f) (KummerField n f)]
  exact kummerLocal_ringElem_mem a b hb _

lemma kummerLocal_const_mem (z : ℂ) :
    algebraMap ℂ (KummerField n f) z ∈ kummerLocalRing a b hb := by
  rw [IsScalarTower.algebraMap_apply ℂ (KummerRing n f) (KummerField n f)]
  exact kummerLocal_ringElem_mem a b hb _

lemma kummerLocal_root_mem :
    AdjoinRoot.root (kummerRat n f) ∈ kummerLocalRing a b hb := by
  rw [← kummerRingMap_root]
  exact kummerLocal_ringElem_mem a b hb _

/-- A polynomial in `x` not vanishing at `a` has its inverse in the local ring at `(a, b)`. -/
lemma kummerLocal_poly_inv_mem (p : ℂ[X]) (hp : p.eval a ≠ 0) :
    (algebraMap ℂ[X] (KummerField n f) p)⁻¹ ∈ kummerLocalRing a b hb := by
  have hmem : algebraMap ℂ[X] (KummerRing n f) p ∈
      (RingHom.ker (kummerEval n f a b hb)).primeCompl := by
    rw [Ideal.primeCompl, Submonoid.mem_mk, Subsemigroup.mem_mk, Set.mem_compl_iff,
      SetLike.mem_coe, RingHom.mem_ker, kummerEval_algebraMap]
    exact hp
  obtain ⟨y, hy⟩ := (IsLocalization.map_units (kummerLocalRing a b hb) ⟨_, hmem⟩).exists_right_inv
  have hcoe : algebraMap (KummerRing n f) (KummerField n f) (algebraMap ℂ[X] (KummerRing n f) p) *
      (y : KummerField n f) = 1 := by
    have hc1 := congrArg (fun z : kummerLocalRing a b hb => (z : KummerField n f)) hy
    simpa using hc1
  rw [IsScalarTower.algebraMap_apply ℂ[X] (KummerRing n f) (KummerField n f),
    inv_eq_of_mul_eq_one_right hcoe]
  exact y.2

/-- **R01c-2b**: the place at a point is a place over `ℂ` in the sense of R01a. -/
lemma kummerPlace_isComplexPlace : IsComplexPlace (kummerPlace a b hb) :=
  ⟨primeValuationSubring_ne_top _ (kummerEval_ker_ne_bot a b hb), kummerLocal_const_mem a b hb⟩

/-- A generator of the local maximal ideal gives the generator condition of R01a. -/
lemma kummerPlace_generator {u : kummerLocalRing a b hb}
    (hu : IsLocalRing.maximalIdeal (kummerLocalRing a b hb) = Ideal.span {u}) :
    ∀ c ∈ kummerPlace a b hb, ∃ g ∈ kummerPlace a b hb,
      KaehlerDifferential.D ℂ (KummerField n f) c =
        g • KaehlerDifferential.D ℂ (KummerField n f) (u : KummerField n f) := by
  intro c hc
  obtain ⟨g, hg⟩ := exists_D_eq_smul_of_span_eq_top (K := KummerField n f)
    (kummerLocal_kaehler_span_eq_top a b hb hu) ⟨c, hc⟩
  exact ⟨g, g.2, hg⟩

/-- **R01c-2b, unramified points**: where `f(a) ≠ 0`, `F·dx` is regular exactly when `F` is in
the local ring. -/
theorem kummer_regularAt_unramified (hfa : f.eval a ≠ 0) (F : KummerField n f) :
    F • KaehlerDifferential.D ℂ (KummerField n f) (kummerX n f) ∈ regularAt (kummerPlace a b hb) ↔
      F ∈ kummerPlace a b hb := by
  set u : kummerLocalRing a b hb :=
    algebraMap (KummerRing n f) (kummerLocalRing a b hb) (kummerShift n f a)
  have hu := kummer_unramified_maximalIdeal a b hb (kummerLocalRing a b hb) hfa
  have hDu : KaehlerDifferential.D ℂ (KummerField n f) (u : KummerField n f) =
      KaehlerDifferential.D ℂ (KummerField n f) (kummerX n f) := by
    have hcoe : (u : KummerField n f) = kummerX n f - algebraMap ℂ (KummerField n f) a := by
      show algebraMap (KummerRing n f) (KummerField n f) (kummerShift n f a) = _
      rw [kummerShift, ← IsScalarTower.algebraMap_apply ℂ[X] (KummerRing n f) (KummerField n f),
        map_sub, C_eq_algebraMap, ← IsScalarTower.algebraMap_apply ℂ ℂ[X] (KummerField n f)]
      rfl
    rw [hcoe, map_sub, Derivation.map_algebraMap, sub_zero]
  rw [mem_regularAt_iff_of_generator u.2 (kummerLocal_const_mem a b hb)
    (kummerPlace_generator a b hb hu), hDu]
  constructor
  · rintro ⟨g, hg, hω⟩
    rw [smul_left_injective (KummerField n f) (kummer_D_x_ne_zero n f) hω]
    exact hg
  · intro hF
    exact ⟨F, hF, rfl⟩

/-- **R01c-2b, ramified points**: where `f(a) = 0`, `F·dx` is regular exactly when `F·yⁿ⁻¹` is in
the local ring: `dx` carries `n − 1` factors of the uniformizer `y`. -/
theorem kummer_regularAt_ramified (hfa : f.eval a = 0) (F : KummerField n f) :
    F • KaehlerDifferential.D ℂ (KummerField n f) (kummerX n f) ∈ regularAt (kummerPlace a b hb) ↔
      F * AdjoinRoot.root (kummerRat n f) ^ (n - 1) ∈ kummerPlace a b hb := by
  set y := AdjoinRoot.root (kummerRat n f)
  set u : kummerLocalRing a b hb :=
    algebraMap (KummerRing n f) (kummerLocalRing a b hb) (AdjoinRoot.root (kummerPoly n f))
  have hu := kummer_ramified_maximalIdeal a b hb (kummerLocalRing a b hb) hfa
  have hucoe : (u : KummerField n f) = y := kummerRingMap_root n f
  -- `f'(x)` is a unit at the simple root `a`
  obtain ⟨k, hk, hka⟩ := exists_factor_of_root f a hfa
  have hder : f.derivative.eval a ≠ 0 := by
    rw [hk, derivative_mul, derivative_sub, derivative_X, derivative_C, sub_zero, one_mul,
      eval_add, eval_mul, eval_sub, eval_X, eval_C, sub_self, zero_mul, add_zero]
    exact hka
  set fp := algebraMap ℂ[X] (KummerField n f) f.derivative
  have hfp0 : fp ≠ 0 := by
    intro h0
    apply hder
    rw [kummerField_polynomial_injective (h0.trans (map_zero _).symm), eval_zero]
  have hn0 : (n : KummerField n f) ≠ 0 := Nat.cast_ne_zero.mpr (NeZero.ne n)
  -- `dx = (n·yⁿ⁻¹ / f'(x))·dy`
  have hdx : KaehlerDifferential.D ℂ (KummerField n f) (kummerX n f) =
      (fp⁻¹ * ((n : KummerField n f) * y ^ (n - 1))) •
        KaehlerDifferential.D ℂ (KummerField n f) y := by
    rw [← smul_smul, kummer_D_root, smul_smul, inv_mul_cancel₀ hfp0, one_smul]
  have hDy : KaehlerDifferential.D ℂ (KummerField n f) y ≠ 0 := by
    intro h0
    apply kummer_D_x_ne_zero n f
    rw [hdx, h0, smul_zero]
  rw [mem_regularAt_iff_of_generator u.2 (kummerLocal_const_mem a b hb)
    (kummerPlace_generator a b hb hu), hucoe, hdx, smul_smul]
  have hfp_mem : fp ∈ kummerLocalRing a b hb := kummerLocal_poly_mem a b hb _
  have hfpinv_mem : fp⁻¹ ∈ kummerLocalRing a b hb := kummerLocal_poly_inv_mem a b hb _ hder
  have hn_mem : (n : KummerField n f) ∈ kummerLocalRing a b hb := by
    rw [show (n : KummerField n f) = algebraMap ℂ (KummerField n f) n by simp]
    exact kummerLocal_const_mem a b hb _
  have hninv_mem : (n : KummerField n f)⁻¹ ∈ kummerLocalRing a b hb := by
    rw [show (n : KummerField n f)⁻¹ = algebraMap ℂ (KummerField n f) (n : ℂ)⁻¹ by simp]
    exact kummerLocal_const_mem a b hb _
  constructor
  · rintro ⟨g, hg, hω⟩
    have hg' : F * (fp⁻¹ * ((n : KummerField n f) * y ^ (n - 1))) = g :=
      smul_left_injective (KummerField n f) hDy hω
    have hfac : F * y ^ (n - 1) = (fp * (n : KummerField n f)⁻¹) * g := by
      rw [← hg']
      field_simp
    rw [mem_kummerPlace_iff, hfac]
    exact Subalgebra.mul_mem _ (Subalgebra.mul_mem _ hfp_mem hninv_mem) hg
  · intro hF
    refine ⟨_, ?_, rfl⟩
    rw [mem_kummerPlace_iff] at hF ⊢
    rw [show F * (fp⁻¹ * ((n : KummerField n f) * y ^ (n - 1))) =
      (fp⁻¹ * (n : KummerField n f)) * (F * y ^ (n - 1)) by ring]
    exact Subalgebra.mul_mem _ (Subalgebra.mul_mem _ hfpinv_mem hn_mem) hF

end Local

/-- **R01c-2b**: an element of the Kummer field lying in the local ring of every point comes
from the coordinate ring, which is the intersection of its localizations at maximal ideals. -/
theorem kummer_mem_range_of_forall_local (g : KummerField n f)
    (hg : ∀ (a b : ℂ) (hb : b ^ n = f.eval a), g ∈ kummerLocalRing a b hb) :
    ∃ r : KummerRing n f, algebraMap (KummerRing n f) (KummerField n f) r = g := by
  have hbot := MaximalSpectrum.iInf_localization_eq_bot (KummerRing n f) (KummerField n f)
  have hmem : g ∈ (⊥ : Subalgebra (KummerRing n f) (KummerField n f)) := by
    rw [← hbot, Algebra.mem_iInf]
    rintro ⟨P, hP⟩
    obtain ⟨a, b, hb, rfl⟩ := (kummerRing_isMaximal_iff P).mp hP
    exact hg a b hb
  rw [Algebra.mem_bot] at hmem
  obtain ⟨r, hr⟩ := hmem
  exact ⟨r, hr⟩

#print axioms kummerLocal_kaehler_span_eq_top
#print axioms kummer_regularAt_unramified
#print axioms kummer_regularAt_ramified
#print axioms kummer_mem_range_of_forall_local

end CurveSymmetry
