import Mathlib.RingTheory.Kaehler.Basic
import Mathlib.RingTheory.Nakayama
import Mathlib.RingTheory.LocalRing.Module
import Mathlib.RingTheory.LocalRing.MaximalIdeal.Basic
import Mathlib.RingTheory.Etale.Kaehler

/-!
# Differentials of a local ring with principal maximal ideal (G09a-2a)

Let `A` be a local `R`-algebra whose residue field is generated by `R` and whose
maximal ideal is generated by one element `u`. Then `Ω[A⁄R]` is generated by
`du`, provided it is finitely generated over `A`.

The proof is Nakayama plus one line of Leibniz: any `x : A` is `r + u·a` with
`r` from `R`, so `dx = a·du + u·da`, and the second term lies in `𝔪·Ω`.

The consequence used later is that the submodule generated by `du` does not
depend on the choice of `u`. For a place of a function field this is the
statement that the order of a differential does not depend on the chosen
uniformizer; no order, divisor or genus is defined here.
-/

namespace CurveSymmetry

set_option autoImplicit false

section

variable {R A : Type*} [CommRing R] [CommRing A] [Algebra R A] [IsLocalRing A]
  [Module.Finite A Ω[A⁄R]]

/-- With a residue field generated by `R` and a principal maximal ideal `(u)`,
the differentials `Ω[A⁄R]` are generated by `du`. -/
theorem localKaehler_span_eq_top {u : A}
    (hres : ∀ x : A, ∃ r : R, x - algebraMap R A r ∈ IsLocalRing.maximalIdeal A)
    (hu : IsLocalRing.maximalIdeal A = Ideal.span {u}) :
    Submodule.span A {KaehlerDifferential.D R A u} = ⊤ := by
  have humem : u ∈ IsLocalRing.maximalIdeal A := by
    rw [hu]; exact Ideal.mem_span_singleton_self u
  refine eq_top_iff.mpr (Submodule.le_of_le_smul_of_le_jacobson_bot
    (Module.finite_def.mp inferInstance) (IsLocalRing.maximalIdeal_le_jacobson ⊥) ?_)
  have hspan : (⊤ : Submodule A Ω[A⁄R]) =
      Submodule.span A (Set.range (KaehlerDifferential.D R A)) :=
    (KaehlerDifferential.span_range_derivation R A).symm
  conv_lhs => rw [hspan]
  rw [Submodule.span_le]
  rintro _ ⟨x, rfl⟩
  obtain ⟨r, hr⟩ := hres x
  rw [hu, Ideal.mem_span_singleton] at hr
  obtain ⟨a, ha⟩ := hr
  have hx : x = algebraMap R A r + u * a := by
    have := sub_eq_iff_eq_add.mp ha
    rw [this]; ring
  refine Submodule.mem_sup.mpr ⟨a • KaehlerDifferential.D R A u,
    Submodule.mem_span_singleton.mpr ⟨a, rfl⟩,
    u • KaehlerDifferential.D R A a,
    Submodule.smul_mem_smul humem Submodule.mem_top, ?_⟩
  rw [hx, map_add, Derivation.map_algebraMap, zero_add,
    (KaehlerDifferential.D R A).leibniz u a, add_comm]

/-- The submodule generated by `du` is independent of the chosen generator of the
maximal ideal: both are everything. -/
theorem localKaehler_span_congr {u u' : A}
    (hres : ∀ x : A, ∃ r : R, x - algebraMap R A r ∈ IsLocalRing.maximalIdeal A)
    (hu : IsLocalRing.maximalIdeal A = Ideal.span {u})
    (hu' : IsLocalRing.maximalIdeal A = Ideal.span {u'}) :
    Submodule.span A {KaehlerDifferential.D R A u} =
      Submodule.span A {KaehlerDifferential.D R A u'} := by
  rw [localKaehler_span_eq_top hres hu, localKaehler_span_eq_top hres hu']

/-- Every differential is a multiple of `du`. -/
theorem localKaehler_exists_smul {u : A}
    (hres : ∀ x : A, ∃ r : R, x - algebraMap R A r ∈ IsLocalRing.maximalIdeal A)
    (hu : IsLocalRing.maximalIdeal A = Ideal.span {u}) :
    ∀ ω : Ω[A⁄R], ∃ c : A, ω = c • KaehlerDifferential.D R A u := by
  intro ω
  have hmem : ω ∈ Submodule.span A {KaehlerDifferential.D R A u} := by
    rw [localKaehler_span_eq_top hres hu]; trivial
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp hmem
  exact ⟨c, hc.symm⟩

end

section Localization

variable {R S A : Type*} [Field R] [CommRing S] [Algebra R S] [CommRing A] [Algebra S A]
  [Algebra R A] [IsScalarTower R S A] [IsLocalRing A] (P : Ideal S) [P.IsPrime]
  [IsLocalization.AtPrime A P]

/-- A residue field generated by the base survives localization: if every element of `S`
differs from a constant by an element of `P`, the same holds in `A = S_P` for its maximal
ideal. Constants are inverted here, so the base is required to be a field. -/
theorem localization_residue (hres : ∀ s : S, ∃ r : R, s - algebraMap R S r ∈ P) (x : A) :
    ∃ r : R, x - algebraMap R A r ∈ IsLocalRing.maximalIdeal A := by
  obtain ⟨s, t, rfl⟩ := IsLocalization.exists_mk'_eq P.primeCompl x
  obtain ⟨rs, hs⟩ := hres s
  obtain ⟨rt, ht⟩ := hres (t : S)
  have htne : rt ≠ 0 := by
    rintro rfl
    refine t.2 ?_
    simpa using ht
  refine ⟨rs * rt⁻¹, ?_⟩
  have key : IsLocalization.mk' A s t - algebraMap R A (rs * rt⁻¹) =
      IsLocalization.mk' A (s - algebraMap R S (rs * rt⁻¹) * t) t := by
    rw [IsLocalization.eq_mk'_iff_mul_eq, sub_mul, IsLocalization.mk'_spec, map_sub, map_mul,
      IsScalarTower.algebraMap_apply R S A]
    simp [map_mul, mul_assoc]
    rw [IsScalarTower.algebraMap_apply R S A rt⁻¹]
  rw [key]
  refine (IsLocalization.AtPrime.mk'_mem_maximal_iff A P _ t).mpr ?_
  have hzero : algebraMap R S rs - algebraMap R S (rs * rt⁻¹) * algebraMap R S rt = 0 := by
    rw [← map_mul, ← map_sub]
    have : rs - rs * rt⁻¹ * rt = 0 := by
      rw [mul_assoc, inv_mul_cancel₀ htne, mul_one, sub_self]
    rw [this, map_zero]
  have hsplit : s - algebraMap R S (rs * rt⁻¹) * (t : S) =
      (s - algebraMap R S rs) - algebraMap R S (rs * rt⁻¹) * ((t : S) - algebraMap R S rt) +
        (algebraMap R S rs - algebraMap R S (rs * rt⁻¹) * algebraMap R S rt) := by ring
  rw [hsplit, hzero, add_zero]
  exact P.sub_mem hs (Ideal.mul_mem_left _ _ ht)

end Localization

section BaseChangeSpan

variable (R S T : Type*) [CommRing R] [CommRing S] [CommRing T] [Algebra R S] [Algebra R T]
  [Algebra S T] [IsScalarTower R S T] [Algebra.FormallyEtale S T]

/-- A single generator of `Ω[S⁄R]` stays a generator after a formally étale base change. -/
theorem kaehler_span_map_eq_top {v : Ω[S⁄R]} (hv : Submodule.span S {v} = ⊤) :
    Submodule.span T {KaehlerDifferential.map R R S T v} = ⊤ := by
  rw [eq_top_iff]
  rintro ω -
  obtain ⟨x, rfl⟩ := (KaehlerDifferential.tensorKaehlerEquivOfFormallyEtale R S T).surjective ω
  induction x using TensorProduct.induction_on with
  | zero => simp
  | tmul a m =>
    have hm : m ∈ Submodule.span S {v} := by rw [hv]; trivial
    obtain ⟨cc, rfl⟩ := Submodule.mem_span_singleton.mp hm
    rw [KaehlerDifferential.tensorKaehlerEquivOfFormallyEtale_apply,
      KaehlerDifferential.mapBaseChange_tmul, map_smul,
      ← IsScalarTower.algebraMap_smul T cc (KaehlerDifferential.map R R S T v), smul_smul]
    exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self _)
  | add x y hx hy =>
    rw [map_add]
    exact Submodule.add_mem _ hx hy

end BaseChangeSpan

#print axioms localKaehler_span_eq_top

end CurveSymmetry
