import Mathlib.RingTheory.Kaehler.Basic
import Mathlib.RingTheory.Nakayama
import Mathlib.RingTheory.LocalRing.Module
import Mathlib.RingTheory.LocalRing.MaximalIdeal.Basic

/-!
# Differentials of a local ring with principal maximal ideal (G09a-2a)

Let `A` be a local `R`-algebra whose residue field is generated by `R` and whose
maximal ideal is generated by one element `u`. Then `Ω[A⁄R]` is generated by
`du`, provided it is finitely generated over `A`.

The proof is Nakayama plus one line of Leibniz: any `x : A` is `r + u·a` with
`r` from `R`, so `dx = a·du + u·da`, and the second term lies in `𝔪·Ω`.

The consequence used later is that the submodule generated by `du` does not
depend on the choice of `u`. For a place of a function field this is the
statement that the order of a differential does not depend on the chosen
uniformizer; no order, divisor or genus is defined here.
-/

namespace CurveSymmetry

set_option autoImplicit false

section

variable {R A : Type*} [CommRing R] [CommRing A] [Algebra R A] [IsLocalRing A]
  [Module.Finite A Ω[A⁄R]]

/-- With a residue field generated by `R` and a principal maximal ideal `(u)`,
the differentials `Ω[A⁄R]` are generated by `du`. -/
theorem localKaehler_span_eq_top {u : A}
    (hres : ∀ x : A, ∃ r : R, x - algebraMap R A r ∈ IsLocalRing.maximalIdeal A)
    (hu : IsLocalRing.maximalIdeal A = Ideal.span {u}) :
    Submodule.span A {KaehlerDifferential.D R A u} = ⊤ := by
  have humem : u ∈ IsLocalRing.maximalIdeal A := by
    rw [hu]; exact Ideal.mem_span_singleton_self u
  refine eq_top_iff.mpr (Submodule.le_of_le_smul_of_le_jacobson_bot
    (Module.finite_def.mp inferInstance) (IsLocalRing.maximalIdeal_le_jacobson ⊥) ?_)
  have hspan : (⊤ : Submodule A Ω[A⁄R]) =
      Submodule.span A (Set.range (KaehlerDifferential.D R A)) :=
    (KaehlerDifferential.span_range_derivation R A).symm
  conv_lhs => rw [hspan]
  rw [Submodule.span_le]
  rintro _ ⟨x, rfl⟩
  obtain ⟨r, hr⟩ := hres x
  rw [hu, Ideal.mem_span_singleton] at hr
  obtain ⟨a, ha⟩ := hr
  have hx : x = algebraMap R A r + u * a := by
    have := sub_eq_iff_eq_add.mp ha
    rw [this]; ring
  refine Submodule.mem_sup.mpr ⟨a • KaehlerDifferential.D R A u,
    Submodule.mem_span_singleton.mpr ⟨a, rfl⟩,
    u • KaehlerDifferential.D R A a,
    Submodule.smul_mem_smul humem Submodule.mem_top, ?_⟩
  rw [hx, map_add, Derivation.map_algebraMap, zero_add,
    (KaehlerDifferential.D R A).leibniz u a, add_comm]

/-- The submodule generated by `du` is independent of the chosen generator of the
maximal ideal: both are everything. -/
theorem localKaehler_span_congr {u u' : A}
    (hres : ∀ x : A, ∃ r : R, x - algebraMap R A r ∈ IsLocalRing.maximalIdeal A)
    (hu : IsLocalRing.maximalIdeal A = Ideal.span {u})
    (hu' : IsLocalRing.maximalIdeal A = Ideal.span {u'}) :
    Submodule.span A {KaehlerDifferential.D R A u} =
      Submodule.span A {KaehlerDifferential.D R A u'} := by
  rw [localKaehler_span_eq_top hres hu, localKaehler_span_eq_top hres hu']

/-- Every differential is a multiple of `du`. -/
theorem localKaehler_exists_smul {u : A}
    (hres : ∀ x : A, ∃ r : R, x - algebraMap R A r ∈ IsLocalRing.maximalIdeal A)
    (hu : IsLocalRing.maximalIdeal A = Ideal.span {u}) :
    ∀ ω : Ω[A⁄R], ∃ c : A, ω = c • KaehlerDifferential.D R A u := by
  intro ω
  have hmem : ω ∈ Submodule.span A {KaehlerDifferential.D R A u} := by
    rw [localKaehler_span_eq_top hres hu]; trivial
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp hmem
  exact ⟨c, hc.symm⟩

end

#print axioms localKaehler_span_eq_top

end CurveSymmetry
