import QuadraticPlaces
import QuadraticDifferentials
import LocalDifferentials

/-!
# Differentials at a point place of the double cover (G09a-2b)

The local ring of the cover at a point place `(c, d)` is the localization of
`ℂ[t][W]/(W² − h)` at the maximal ideal of that point. It is a discrete
valuation ring, its residue field is `ℂ`, so G09a-2a applies: its differentials
are generated by `du` for any uniformizer `u`, and that submodule does not
depend on which uniformizer is chosen.

This is the local input for an order of a differential at a place. The order
itself, and its value on `dt`, are not defined here.
-/

namespace CurveSymmetry

set_option autoImplicit false
open Polynomial

section

variable (h : ℂ[X]) [Fact (Squarefree h)] [Fact (Irreducible (quadRat h))]

instance quadRing_scalarTower_complex : IsScalarTower ℂ (QuadRing h) (QuadField h) :=
  IsScalarTower.of_algebraMap_eq fun x => by
    rw [IsScalarTower.algebraMap_apply ℂ ℂ[X] (QuadField h),
      IsScalarTower.algebraMap_apply ℂ[X] (QuadRing h) (QuadField h),
      IsScalarTower.algebraMap_apply ℂ ℂ[X] (QuadRing h)]

variable (c d : ℂ) (hd : d ^ 2 = h.eval c)

/-- The local ring of the double cover at the point place `(c, d)`. -/
noncomputable abbrev quadLocalRing : Subalgebra (QuadRing h) (QuadField h) :=
  primeLocalization (QuadField h) (RingHom.ker (quadEval h c d hd))

noncomputable instance quadLocalRing_essFiniteType_quadRing :
    Algebra.EssFiniteType (QuadRing h) (quadLocalRing h c d hd) :=
  Algebra.EssFiniteType.of_isLocalization (S := (quadLocalRing h c d hd))
    (RingHom.ker (quadEval h c d hd)).primeCompl

noncomputable instance quadLocalRing_essFiniteType :
    Algebra.EssFiniteType ℂ (quadLocalRing h c d hd) :=
  Algebra.EssFiniteType.comp ℂ (QuadRing h) (quadLocalRing h c d hd)

instance quadLocalRing_dvr : IsDiscreteValuationRing (quadLocalRing h c d hd) :=
  primeLocalization_dvr _ (quadEval_ker_ne_bot h c d hd)

omit [Fact (Squarefree h)] [Fact (Irreducible (quadRat h))] in
/-- Constants of `ℂ` represent every residue of the coordinate ring at the point. -/
theorem quadRing_residue (s : QuadRing h) :
    ∃ r : ℂ, s - algebraMap ℂ (QuadRing h) r ∈ RingHom.ker (quadEval h c d hd) := by
  refine ⟨quadEval h c d hd s, ?_⟩
  have hconst : quadEval h c d hd (algebraMap ℂ (QuadRing h) (quadEval h c d hd s)) =
      quadEval h c d hd s := by
    rw [IsScalarTower.algebraMap_apply ℂ ℂ[X] (QuadRing h), ← Polynomial.C_eq_algebraMap,
      show (algebraMap ℂ[X] (QuadRing h)) = AdjoinRoot.of (quadPoly h) from rfl,
      quadEval_of, eval_C]
  rw [RingHom.mem_ker, map_sub, hconst, sub_self]

/-- The residue field of the local ring at a point place is generated by the constants. -/
theorem quadLocal_residue (x : quadLocalRing h c d hd) :
    ∃ r : ℂ, x - algebraMap ℂ (quadLocalRing h c d hd) r ∈
      IsLocalRing.maximalIdeal (quadLocalRing h c d hd) :=
  localization_residue (RingHom.ker (quadEval h c d hd)) (quadRing_residue h c d hd) x

/-- **G09a-2b**: at a point place, the differentials of the local ring are generated by
`du` for any generator `u` of the maximal ideal. -/
theorem quadLocal_kaehler_span_eq_top {u : quadLocalRing h c d hd}
    (hu : IsLocalRing.maximalIdeal (quadLocalRing h c d hd) = Ideal.span {u}) :
    Submodule.span (quadLocalRing h c d hd)
      {KaehlerDifferential.D ℂ (quadLocalRing h c d hd) u} = ⊤ :=
  localKaehler_span_eq_top (quadLocal_residue h c d hd) hu

/-- A uniformizer exists at every point place, and its differential generates. -/
theorem quadLocal_exists_uniformizer :
    ∃ u : quadLocalRing h c d hd,
      IsLocalRing.maximalIdeal (quadLocalRing h c d hd) = Ideal.span {u} ∧
        Submodule.span (quadLocalRing h c d hd)
          {KaehlerDifferential.D ℂ (quadLocalRing h c d hd) u} = ⊤ := by
  obtain ⟨u, hu⟩ := IsDiscreteValuationRing.exists_irreducible (quadLocalRing h c d hd)
  have hspan := (IsDiscreteValuationRing.irreducible_iff_uniformizer u).mp hu
  exact ⟨u, hspan, quadLocal_kaehler_span_eq_top h c d hd hspan⟩

/-- The generated submodule, hence any order read off from it, does not depend on the
chosen uniformizer. -/
theorem quadLocal_kaehler_span_congr {u u' : quadLocalRing h c d hd}
    (hu : IsLocalRing.maximalIdeal (quadLocalRing h c d hd) = Ideal.span {u})
    (hu' : IsLocalRing.maximalIdeal (quadLocalRing h c d hd) = Ideal.span {u'}) :
    Submodule.span (quadLocalRing h c d hd)
        {KaehlerDifferential.D ℂ (quadLocalRing h c d hd) u} =
      Submodule.span (quadLocalRing h c d hd)
        {KaehlerDifferential.D ℂ (quadLocalRing h c d hd) u'} :=
  localKaehler_span_congr (quadLocal_residue h c d hd) hu hu'

end

variable {m : ℕ} {α : ℂ} [hm : Fact (0 < m)] [ha : Fact (α ≠ star α)]

/-- G09a-2b for the family: at every point place of the family's double cover, the
differentials of the local ring are generated by `du` for any uniformizer `u`. -/
theorem family_local_kaehler_uniformizer (c d : ℂ) (hd : d ^ 2 = (familyH m α).eval c) :
    ∃ u : quadLocalRing (familyH m α) c d hd,
      IsLocalRing.maximalIdeal (quadLocalRing (familyH m α) c d hd) = Ideal.span {u} ∧
        Submodule.span (quadLocalRing (familyH m α) c d hd)
          {KaehlerDifferential.D ℂ (quadLocalRing (familyH m α) c d hd) u} = ⊤ :=
  quadLocal_exists_uniformizer _ c d hd

#print axioms quadLocal_kaehler_span_eq_top
#print axioms family_local_kaehler_uniformizer

end CurveSymmetry
